namespace: jenkins

jenkins:
  image: "jenkins/jenkins:lts"
  serviceAccountName: jenkins
  replicas: 1
  storage:
    accessMode: ReadWriteOnce
    size: 8Gi
    pv:
      name: jenkins-pv
      storageClassName: local-storage
      hostPath: "/tmp/jenkins-volume"
    pvc:
      name: jenkins-pvc

  resources:
    limits:
      memory: "2Gi"
      cpu: "1000m"
    requests:
      memory: "500Mi"
      cpu: "500m"

  service:
    nodePort: 30000

  installPlugins:
    - kubernetes:1.31.3
    - workflow-aggregator:2.6
    - git:4.15.2
    - configuration-as-code:1.57
    - cloudbees-credentials:1.0
    - jacoco:3.3.2
    - email-ext:2.95
    - sonar:2.15
    - aws-credentials:1.0.0
    - docker-workflow:1.28
    - build-timeout:1.25
    - timestamper:1.18.1

  JCasC:
    defaultConfig: true
    securityRealm: |-
      local:
        allowsSignup: false
        enableCaptcha: false
        users:
        - id: "${chart-admin-username}"
          name: "Jenkins Admin"
          password: "${chart-admin-password}"
        - id: "rsschool"
          name: "RS School"
          password: "rs-school"
    authorizationStrategy: |-
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false
    configScripts:
      kubernetes-cloud: |-
        jenkins:
          clouds:
            - kubernetes:
                name: "kubernetes"
                serverUrl: "https://kubernetes.default"
                jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
                jenkinsTunnel: "jenkins.jenkins.svc.cluster.local:50000"
                containerCapStr: "10"
                maxRequestsPerHostStr: "32"
                namespace: "jenkins"
                templates:
                  - name: "jenkins-agent"
                    namespace: "jenkins"
                    label: "jenkins-agent"
                    containers:
                      - name: "jnlp"
                        image: "jenkins/inbound-agent:4.11-5-jdk17"
                        workingDir: "/home/jenkins/agent"
                        command: ""
                        args: ""
                        resourceRequestCpu: "500m"
                        resourceRequestMemory: "512Mi"
                        resourceLimitCpu: "1000m"
                        resourceLimitMemory: "1Gi"
                    yaml: |
                      spec:
                        serviceAccountName: jenkins
                        securityContext:
                          runAsUser: 1000
                          fsGroup: 1000
                        containers:
                        - name: jnlp
                          image: jenkins/inbound-agent:4.11-5-jdk17
                          workingDir: /home/jenkins/agent
                          command:
                          - /usr/local/bin/jenkins-agent
                          args:
                          - -url
                          - $(JENKINS_URL)
                          - $(JENKINS_SECRET)
                          - $(JENKINS_AGENT_NAME)
                          volumeMounts:
                          - name: workspace-volume
                            mountPath: /home/jenkins/agent
                        volumes:
                        - name: workspace-volume
                          emptyDir: {}
      welcome-message: |-
        jenkins:
          systemMessage: Welcome to our RS School DevOps 2025 Q2 course CI\CD server.  This Jenkins is configured and managed 'as code'.
        jobs:
           - script: >
               pipelineJob('test-job') {
                 definition {
                   cps {
                     script('''
                       pipeline {
                               agent any
                               stages {
                                   stage('Stage 1') {
                                       steps {
                                           echo 'Hello World!'
                                       }
                                   }
                                   stage('Stage 2') {
                                       steps {
                                           echo 'Is it me your looking for'
                                       }
                                   }
                               }
        
                       }
                     '''.stripIndent())
                     sandbox()
                   }
                 }
               }