apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-notification-channels
  namespace: monitoring
  labels:
    app: grafana
data:
  notifiers.yaml: |
    notifiers:
      - name: email-notifications
        type: email
        uid: email1
        org_id: 1
        is_default: true
        settings:
          addresses: "your-email@gmail.com"
        secure_settings:
          password: "your-app-password"
      
      - name: slack-notifications
        type: slack
        uid: slack1
        org_id: 1
        is_default: false
        settings:
          url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
          recipient: "#alerts"
          mentionChannel: "here" 