apiVersion: v1
kind: Secret
metadata:
  name: grafana-smtp-secret
  namespace: monitoring
  labels:
    app: grafana
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  # echo -n "your-email@gmail.com" | base64
  smtp-user: eW91ci1lbWFpbEBnbWFpbC5jb20=
  # echo -n "your-app-password" | base64
  smtp-password: eW91ci1hcHAtcGFzc3dvcmQ=
  # echo -n "your-email@gmail.com" | base64
  smtp-from: eW91ci1lbWFpbEBnbWFpbC5jb20= 